---
- name: Include OS specific vars
  tags: blackfire
  include_vars: "os_family/{{ ansible_os_family }}.yml"

- include: os_family/Debian.yml
  tags: blackfire
  when: ansible_os_family == 'Debian'

- include: os_family/RedHat.yml
  tags: blackfire
  when: ansible_os_family == 'RedHat'

- name: Create agent configuration
  tags: blackfire
  template:
    src=agent.j2
    dest={{ blackfire_directory }}/agent
    owner=0
    group=0
    mode=0644
  register: agent_configuration_state

- name: Restart Blackfire, PHP and NGINX services.
  tags: blackfire
  sudo: true
  notify:
    - reload blackfire
    - reload php-fpm
    - reload nginx
  when: agent_configuration_state|changed