---
- name: reload blackfire
  service:
    name: blackfire-agent
    state: restarted

- name: reload php-fpm
  service:
    name: php7.2-fpm
    state: reloaded

- name: reload nginx
  service:
    name: nginx
    state: reloaded